#!/usr/bin/env node
/**
 * Build the browser bundle: lib/client.js in the dsh client-module format
 * (`window.__ModuleLoader__.load({ id, factory })`).
 *
 * The bundle is assembled from deliberately module-system-neutral source
 * files (src/client/browser.js — no import/export), so "building" is a plain
 * concatenation — zero bundler dependencies. The same file is loaded
 * directly by Node tests via node:vm.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'))
const browserSrc = readFileSync(join(root, 'src/client/browser.js'), 'utf8')

const bundle = `// Generated by scripts/build-client.mjs from src/client/browser.js — do not edit.
window.__ModuleLoader__.load({
\tid: ${JSON.stringify(pkg.name)},
\tfactory: (require) => {
\t\tvar module = { exports: {} };
\t\tvar exports = module.exports;
\t\tObject.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
\t\tvar React = require("react");
${browserSrc}
\t\texports.apply = SessionDeleteBrowser.browserApply;
\t\texports.inject = ["slots", "workspaces"];
\t\treturn module.exports;
\t}
});
`

mkdirSync(join(root, 'lib'), { recursive: true })
writeFileSync(join(root, 'lib/client.js'), bundle)
console.log('client bundle written:', join(root, 'lib/client.js'), `(${Buffer.byteLength(bundle)} bytes)`)